apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: ecommerce
  namespace: ecommerce

spec:
  replicas: 2

  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app: ecommerce

  template:
    metadata:
      labels:
        app: ecommerce

    spec:
      containers:
        - name: ecommerce

          image: 360967147235.dkr.ecr.ap-south-1.amazonaws.com/ecommerce:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 3006

          envFrom:
            - configMapRef:
                name: ecommerce-config

            - secretRef:
                name: ecommerce-secret

          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /
              port: 3006

            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: 3006

            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

  strategy:

    blueGreen:

      activeService: ecommerce-active

      previewService: ecommerce-preview

      autoPromotionEnabled: false

      previewReplicaCount: 2

      scaleDownDelaySeconds: 30
