apiVersion: v1
kind: Secret

metadata:
  name: ecommerce-secret
  namespace: ecommerce

type: Opaque

stringData:
  EMAIL_USER: "your-email@gmail.com"
  EMAIL_PASS: "your-app-password"
  MONGO_URI: "mongodb://mongodb-service:27017/shopnest"
