services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: quickcartdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

