version: "3.9"

services:
  db:
    image: mysql:8
    container_name: ecommerce_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quickcartdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./quickcart.sql:/docker-entrypoint-initdb.d/quickcart.sql

  app:
    build: .
    container_name: ecommerce_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: quickcartdb
    depends_on:
      - db
