name: Build, Push and Deploy to EKS

on:
  push:
    branches:
      - master

env:
  AWS_REGION: ap-south-1
  CLUSTER_NAME: Ecommerce
  ECR_REPOSITORY: ecommerce

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t $ECR_REPOSITORY:${{ github.sha }} .

      - name: Tag Docker Images
        run: |
          docker tag $ECR_REPOSITORY:${{ github.sha }} \
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}

          docker tag $ECR_REPOSITORY:${{ github.sha }} \
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest

      - name: Push Docker Images
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}

          docker push \
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
          --region $AWS_REGION \
          --name $CLUSTER_NAME

      - name: Update Rollout Image
        run: |
          IMAGE=${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}

          sed -i "s|image: .*|image: $IMAGE|g" k8s/backend/rollout.yaml

      - name: Deploy Rollout
        run: |
          kubectl apply -f k8s/backend/rollout.yaml

      - name: Wait for Rollout
        run: |
          kubectl rollout status rollout/ecommerce \
          -n ecommerce \
          --timeout=300s

      - name: Show Rollout
        run: |
          kubectl get rollout -n ecommerce
